### ISSUE TITLE
Runaway errors if error occurs during --mode trade

### ISSUE THREAD

**Issue by zacuke** [r0fls/soad#93]
So I started /pull/92 but I think the problem might need to be resolved more elegantly.

Basically, if anything happens during the execution of 

`python main.py --mode trade --config examples\single-broker.yaml`

Since it's under a `while True` it just runs away blowing up over and over again. I think some errors might be transient and you don't always want it to bomb out, but some errors are non-resolvable and should just exit out.

What are your thoughts on what I could do to build a better error handling system during Trading loop? The simplest thing I can think of is an error count, so it at least retries some transient errors. Maybe a back off mechanism so it retries only after a few seconds? I'll keep thinking about it.

**Comment by r0fls** [comment]
Thanks @zacuke! So I think what you've done is a nice first step. To be honest I think it might be worth revisiting the single entrypoint design here across services. That being said, we have to be cautious (surgical, even) when changing some things, since I am running this with real money as a side project, and don't like to show up to work while my trading system is on fire 😅 

So, if we think we can make that change (factor out the single entrypoint) in a safe, iterative manner, that would probably be my vote here.

That being said, that may be a larger task than you're up for right now. Happy to put some additional validation in place and/or an error counter as well here in the short term.

**Comment by zacuke** [comment]
Maybe you've already considered this, but you should create a `stable` branch that you deploy to your prod containers. Then you never get changes out there unless you manually do a merge to `stable` when you are ready.

**Comment by r0fls** [comment]
Thanks, I was publishing versions for a while but I'm building up features and fixes right now, should probably do another release at some point. However most of the new changes I've added recently are directly related to fixes I need for live strategies at the moment. Namely, async everything for running higher frequency trading, accounting errors related to selling short, order management improvements. So, I basically have had to test them in the wild, to a certain degree. Just carefully 🙂

**Comment by zacuke** [comment]
I guess your main branch might have been your stable branch before I came along :confounded:
 
Well, the issue of the runaway outer loop is resolved with my latest pull request

I see there's lots of inner code with `except Exception as e:` - I think a lot of that might need to be refactored so there's just a single catch at the topmost of it all, but I definitely don't have enough familiarity yet to know if that is a good idea or not

**Comment by r0fls** [comment]
Ha, nope, I've been the one breaking things! 🤡 

All in good fun though 😄
